import { IMG } from "./images";
import type { Category, Hours, Operator } from "./types";

export const CITIES = ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Enugu", "Benin City"] as const;

export const CATEGORIES: Category[] = [
  { id: "hair", name: "Hair", tagline: "Braids, silk press, wigs & colour", image: IMG.hairStyling },
  { id: "makeup", name: "Makeup", tagline: "Bridal, editorial & soft glam", image: IMG.makeupFace },
  { id: "nails", name: "Nails", tagline: "Gel, acrylics & nail art", image: IMG.nailsManicure },
  { id: "spa", name: "Spa & Skin", tagline: "Facials, massage & rituals", image: IMG.spaMassage },
  { id: "barbing", name: "Barbing", tagline: "Fades, beard sculpting & shaves", image: IMG.barberCut },
  { id: "lashes", name: "Lashes & Brows", tagline: "Extensions, lamination & tint", image: IMG.makeupBrushes },
];

const weekdays = (open: string, close: string, sat?: [string, string], sun?: [string, string]): Hours => ({
  mon: { open, close },
  tue: { open, close },
  wed: { open, close },
  thu: { open, close },
  fri: { open, close },
  sat: sat ? { open: sat[0], close: sat[1] } : { open, close },
  sun: sun ? { open: sun[0], close: sun[1] } : null,
});

export const SEED_OPERATORS: Operator[] = [
  {
    slug: "maison-adaeze-ikoyi",
    name: "Maison Adaeze",
    kind: "Salon",
    categories: ["hair", "lashes"],
    city: "Lagos",
    area: "Ikoyi",
    address: "14 Bourdillon Road, Ikoyi, Lagos",
    phone: "+234 801 000 1101",
    email: "hello@maisonadaeze.ng",
    instagram: "maisonadaeze",
    rating: 4.9,
    reviewCount: 312,
    priceTier: 4,
    cover: IMG.salonInterior,
    gallery: [IMG.hairStyling, IMG.hairColour, IMG.salonChairs, IMG.hairWash],
    lead: { name: "Adaeze Okafor", title: "Creative Director", avatar: IMG.portraitA },
    tagline: "Couture hair artistry in the heart of Ikoyi",
    bio: "Maison Adaeze is a private hair atelier for women who treat their crown as an heirloom. From precision silk presses to bespoke unit installs and heritage braiding, every appointment begins with a consultation and ends with a finish that photographs beautifully.",
    services: [
      { id: "s1", name: "Signature Silk Press", durationMins: 120, price: 45000, description: "Deep cleanse, steam treatment and a glass-finish press." },
      { id: "s2", name: "Knotless Braids (mid-back)", durationMins: 300, price: 85000 },
      { id: "s3", name: "Bespoke Frontal Install", durationMins: 180, price: 70000 },
      { id: "s4", name: "Colour Consultation + Gloss", durationMins: 90, price: 38000 },
      { id: "s5", name: "Classic Lash Set", durationMins: 90, price: 30000 },
    ],
    hours: weekdays("09:00", "19:00", ["08:00", "20:00"], ["12:00", "17:00"]),
    homeService: true,
    verified: true,
    featured: true,
    plan: "signature",
    reviews: [
      { author: "Tolu A.", rating: 5, date: "2026-08-30", text: "The silk press lasted two full weeks. The lounge feels like a private members' club." },
      { author: "Chioma N.", rating: 5, date: "2026-08-12", text: "Booked my wedding-week hair here. Calm, punctual and absolutely flawless." },
      { author: "Ife O.", rating: 4, date: "2026-07-21", text: "Beautiful braids, very neat parting. Slightly longer than quoted, but worth it." },
    ],
    createdAt: "2025-11-02T10:00:00.000Z",
  },
  {
    slug: "the-gilded-brush-lekki",
    name: "The Gilded Brush",
    kind: "Studio",
    categories: ["makeup", "lashes"],
    city: "Lagos",
    area: "Lekki Phase 1",
    address: "7 Admiralty Way, Lekki Phase 1, Lagos",
    phone: "+234 802 000 2202",
    email: "book@gildedbrush.ng",
    instagram: "thegildedbrush",
    rating: 4.8,
    reviewCount: 228,
    priceTier: 3,
    cover: IMG.makeupFace,
    gallery: [IMG.makeupBrushes, IMG.makeupFlatlay, IMG.makeupProducts, IMG.salonLounge],
    lead: { name: "Temi Bakare", title: "Lead Makeup Artist", avatar: IMG.portraitB },
    tagline: "Soft glam, bridal & editorial faces",
    bio: "A light-filled studio for skin-first makeup. Temi and her team specialise in melanin-rich complexions, long-wear bridal looks and on-set editorial work, with travel available across Lagos for weddings and shoots.",
    services: [
      { id: "s1", name: "Soft Glam", durationMins: 75, price: 35000 },
      { id: "s2", name: "Bridal Makeup (with trial)", durationMins: 180, price: 250000, description: "Includes a trial session two weeks before the big day." },
      { id: "s3", name: "Editorial / Photoshoot", durationMins: 90, price: 60000 },
      { id: "s4", name: "Brow Lamination + Tint", durationMins: 60, price: 25000 },
    ],
    hours: weekdays("08:00", "18:00", ["06:00", "20:00"], ["10:00", "16:00"]),
    homeService: true,
    verified: true,
    featured: true,
    plan: "signature",
    reviews: [
      { author: "Amaka E.", rating: 5, date: "2026-09-01", text: "My makeup lasted from 7am church to the after-party. Unreal." },
      { author: "Bisi K.", rating: 5, date: "2026-08-15", text: "Temi understands dark skin like nobody else. Booking was so easy." },
    ],
    createdAt: "2025-12-10T10:00:00.000Z",
  },
  {
    slug: "lacquer-lounge-wuse",
    name: "Lacquer Lounge",
    kind: "Studio",
    categories: ["nails"],
    city: "Abuja",
    area: "Wuse II",
    address: "22 Aminu Kano Crescent, Wuse II, Abuja",
    phone: "+234 803 000 3303",
    email: "hi@lacquerlounge.ng",
    instagram: "lacquerlounge.abj",
    rating: 4.7,
    reviewCount: 184,
    priceTier: 2,
    cover: IMG.nailsManicure,
    gallery: [IMG.nailsArt, IMG.makeupProducts, IMG.salonLounge],
    lead: { name: "Hauwa Sani", title: "Founder & Nail Artist", avatar: IMG.portraitD },
    tagline: "Structured gel, chrome & hand-painted art",
    bio: "Abuja's go-to nail bar for clean, long-lasting sets. Every tool is autoclave-sterilised, and our artists are trained in Russian manicure, builder gel and freehand nail art.",
    services: [
      { id: "s1", name: "Gel Manicure", durationMins: 60, price: 15000 },
      { id: "s2", name: "Acrylic Full Set", durationMins: 120, price: 28000 },
      { id: "s3", name: "Luxury Pedicure", durationMins: 75, price: 20000 },
      { id: "s4", name: "Custom Nail Art (per set)", durationMins: 45, price: 12000 },
    ],
    hours: weekdays("10:00", "20:00", ["09:00", "21:00"], ["13:00", "18:00"]),
    homeService: false,
    verified: true,
    featured: true,
    plan: "signature",
    reviews: [
      { author: "Zainab M.", rating: 5, date: "2026-08-28", text: "Cleanest nail bar in Abuja. My chrome set lasted three weeks." },
      { author: "Rita U.", rating: 4, date: "2026-08-02", text: "Lovely ambience and very careful cuticle work." },
    ],
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    slug: "sanctuary-spa-maitama",
    name: "Sanctuary Spa & Skin",
    kind: "Spa",
    categories: ["spa"],
    city: "Abuja",
    area: "Maitama",
    address: "5 Gana Street, Maitama, Abuja",
    phone: "+234 804 000 4404",
    email: "relax@sanctuaryspa.ng",
    rating: 4.9,
    reviewCount: 402,
    priceTier: 4,
    cover: IMG.spaRoom,
    gallery: [IMG.spaMassage, IMG.spaTreatment, IMG.facial, IMG.skincare],
    lead: { name: "Dr. Ngozi Eze", title: "Aesthetician", avatar: IMG.portraitE },
    tagline: "Clinical skincare meets slow, sensory rituals",
    bio: "Five treatment suites, a steam room and a relaxation lounge set in a quiet Maitama villa. Our therapists pair medical-grade skincare with traditional techniques for results you can see and feel.",
    services: [
      { id: "s1", name: "Signature Hydrafacial", durationMins: 60, price: 55000 },
      { id: "s2", name: "Deep Tissue Massage (90 min)", durationMins: 90, price: 45000 },
      { id: "s3", name: "Couples Retreat", durationMins: 120, price: 120000 },
      { id: "s4", name: "Chemical Peel", durationMins: 45, price: 40000 },
    ],
    hours: weekdays("09:00", "21:00", ["09:00", "21:00"], ["11:00", "19:00"]),
    homeService: false,
    verified: true,
    featured: true,
    plan: "signature",
    reviews: [
      { author: "Kemi F.", rating: 5, date: "2026-09-05", text: "The hydrafacial here is the best money I've spent this year." },
      { author: "Obinna C.", rating: 5, date: "2026-08-18", text: "Booked a couples retreat for our anniversary. Impeccable service." },
    ],
    createdAt: "2025-10-20T10:00:00.000Z",
  },
  {
    slug: "kings-and-co-barbers-vi",
    name: "Kings & Co. Barbers",
    kind: "Barbershop",
    categories: ["barbing"],
    city: "Lagos",
    area: "Victoria Island",
    address: "31 Adeola Odeku Street, Victoria Island, Lagos",
    phone: "+234 805 000 5505",
    email: "chair@kingsandco.ng",
    instagram: "kingsandco.vi",
    rating: 4.8,
    reviewCount: 519,
    priceTier: 3,
    cover: IMG.barberShop,
    gallery: [IMG.barberCut, IMG.barberChair, IMG.salonChairs],
    lead: { name: "Seun Adeyemi", title: "Master Barber", avatar: IMG.portraitC },
    tagline: "The gentleman's chair, reimagined",
    bio: "Precision fades, hot-towel shaves and beard sculpting in a leather-and-brass barbershop. Walk in for a cold drink, walk out looking like the main character.",
    services: [
      { id: "s1", name: "Signature Cut + Hot Towel", durationMins: 45, price: 15000 },
      { id: "s2", name: "Skin Fade", durationMins: 40, price: 12000 },
      { id: "s3", name: "Beard Sculpt & Oil", durationMins: 30, price: 8000 },
      { id: "s4", name: "The Full Royal (cut, shave, facial)", durationMins: 90, price: 35000 },
    ],
    hours: weekdays("08:00", "21:00", ["08:00", "22:00"], ["12:00", "20:00"]),
    homeService: true,
    verified: true,
    featured: true,
    plan: "signature",
    reviews: [
      { author: "David O.", rating: 5, date: "2026-09-10", text: "Cleanest fade in Lagos, and they actually keep to appointment times." },
      { author: "Emeka J.", rating: 5, date: "2026-08-24", text: "The Full Royal is a must before any big event." },
    ],
    createdAt: "2025-09-01T10:00:00.000Z",
  },
  {
    slug: "crown-braiding-studio-gra",
    name: "Crown Braiding Studio",
    kind: "Independent stylist",
    categories: ["hair"],
    city: "Port Harcourt",
    area: "Old GRA",
    address: "9 Forces Avenue, Old GRA, Port Harcourt",
    phone: "+234 806 000 6606",
    email: "crownbraids@glee.ng",
    rating: 4.8,
    reviewCount: 143,
    priceTier: 2,
    cover: IMG.hairStyling,
    gallery: [IMG.hairCut, IMG.hairWash, IMG.hairColour],
    lead: { name: "Blessing Ikwuemesi", title: "Braid Artist", avatar: IMG.portraitB },
    tagline: "Neat parts, light braids, zero tension",
    bio: "Protective styles done gently. Blessing is known for featherweight knotless braids, fulani styles and kids' braiding, with home visits across Port Harcourt.",
    services: [
      { id: "s1", name: "Knotless Braids (medium)", durationMins: 300, price: 45000 },
      { id: "s2", name: "Fulani Braids", durationMins: 240, price: 38000 },
      { id: "s3", name: "Cornrows (straight back)", durationMins: 90, price: 12000 },
      { id: "s4", name: "Kids' Braids", durationMins: 120, price: 15000 },
    ],
    hours: weekdays("08:00", "18:00", ["07:00", "19:00"]),
    homeService: true,
    verified: false,
    featured: false,
    plan: "essential",
    reviews: [{ author: "Ebi T.", rating: 5, date: "2026-08-20", text: "No headache, no tension bumps. She's the one." }],
    createdAt: "2026-03-11T10:00:00.000Z",
  },
  {
    slug: "velvet-lash-bar-ikeja",
    name: "Velvet Lash Bar",
    kind: "Studio",
    categories: ["lashes", "makeup"],
    city: "Lagos",
    area: "Ikeja GRA",
    address: "3 Isaac John Street, Ikeja GRA, Lagos",
    phone: "+234 807 000 7707",
    email: "lashes@velvetbar.ng",
    rating: 4.6,
    reviewCount: 97,
    priceTier: 2,
    cover: IMG.makeupBrushes,
    gallery: [IMG.makeupFace, IMG.makeupFlatlay, IMG.salonLounge],
    lead: { name: "Funke Adebayo", title: "Lash Technician", avatar: IMG.portraitD },
    tagline: "Hybrid, volume & wispy sets that last",
    bio: "A boutique lash bar with plush beds, curated playlists and certified technicians. We only use medical-grade adhesives and individually fan every volume set.",
    services: [
      { id: "s1", name: "Classic Full Set", durationMins: 90, price: 22000 },
      { id: "s2", name: "Hybrid Full Set", durationMins: 120, price: 28000 },
      { id: "s3", name: "Mega Volume", durationMins: 150, price: 35000 },
      { id: "s4", name: "Lash Refill (2 weeks)", durationMins: 60, price: 14000 },
    ],
    hours: weekdays("10:00", "19:00", ["09:00", "19:00"]),
    homeService: false,
    verified: true,
    featured: false,
    plan: "essential",
    reviews: [{ author: "Nkechi A.", rating: 5, date: "2026-09-02", text: "Wispy set was exactly my reference picture." }],
    createdAt: "2026-04-01T10:00:00.000Z",
  },
  {
    slug: "glow-theory-skin-clinic-gra",
    name: "Glow Theory Skin Clinic",
    kind: "Spa",
    categories: ["spa"],
    city: "Enugu",
    area: "Independence Layout",
    address: "12 Nike Lake Road, Independence Layout, Enugu",
    phone: "+234 808 000 8808",
    email: "care@glowtheory.ng",
    rating: 4.7,
    reviewCount: 76,
    priceTier: 3,
    cover: IMG.facial,
    gallery: [IMG.skincare, IMG.spaTreatment, IMG.spaRoom],
    lead: { name: "Ugochi Nwosu", title: "Skin Therapist", avatar: IMG.portraitE },
    tagline: "Results-driven facials for melanin-rich skin",
    bio: "Targeted treatments for hyperpigmentation, acne and texture, designed around a thorough skin analysis. Calm, clinical and wonderfully relaxing.",
    services: [
      { id: "s1", name: "Skin Analysis + Custom Facial", durationMins: 75, price: 30000 },
      { id: "s2", name: "Microneedling", durationMins: 60, price: 65000 },
      { id: "s3", name: "Back Facial", durationMins: 45, price: 22000 },
    ],
    hours: weekdays("09:00", "18:00", ["10:00", "16:00"]),
    homeService: false,
    verified: true,
    featured: false,
    plan: "essential",
    reviews: [{ author: "Adaora I.", rating: 5, date: "2026-08-09", text: "My dark spots have faded so much in two months." }],
    createdAt: "2026-05-18T10:00:00.000Z",
  },
  {
    slug: "atelier-noir-hair-gwarinpa",
    name: "Atelier Noir",
    kind: "Salon",
    categories: ["hair", "makeup", "nails"],
    city: "Abuja",
    area: "Gwarinpa",
    address: "1st Avenue, Gwarinpa, Abuja",
    phone: "+234 809 000 9909",
    email: "studio@ateliernoir.ng",
    rating: 4.6,
    reviewCount: 158,
    priceTier: 3,
    cover: IMG.salonLounge,
    gallery: [IMG.hairColour, IMG.makeupProducts, IMG.nailsArt, IMG.salonChairs],
    lead: { name: "Rukayat Bello", title: "Salon Owner", avatar: IMG.portraitA },
    tagline: "One chair for your whole look",
    bio: "Hair, face and hands under one roof. Atelier Noir's multi-disciplinary team can take you from wash day to full glam in a single, well-choreographed appointment.",
    services: [
      { id: "s1", name: "Wash, Treat & Style", durationMins: 90, price: 20000 },
      { id: "s2", name: "Full Glam Package", durationMins: 180, price: 75000, description: "Hair styling, soft glam and gel manicure." },
      { id: "s3", name: "Wig Revamp", durationMins: 120, price: 25000 },
      { id: "s4", name: "Gel Manicure", durationMins: 60, price: 12000 },
    ],
    hours: weekdays("09:00", "19:00", ["08:00", "20:00"], ["13:00", "18:00"]),
    homeService: true,
    verified: true,
    featured: true,
    plan: "signature",
    reviews: [{ author: "Maryam S.", rating: 5, date: "2026-09-12", text: "Did my hair, face and nails for a dinner in three hours flat." }],
    createdAt: "2026-02-22T10:00:00.000Z",
  },
];
